### ISSUE TITLE
Key Generator

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedShopSystem#1]
It would be nice if there was a way for users to instead buy keys that are generated on the spot, or for it to pull from a list of keys, and for them to be verifiable, I can get that this is a bit of a stretch for the original intentions of this feature.

**Comment by 3D-I** [comment]
For special requests like this, you should contact us at our site.

https://phpbbstudio.com/request

Thanks.

**Comment by mrgoldy** [comment]
No idea what kind of keys you are talking about nor what they should do.
But if you want a custom item type to be build, you can make a request over at the Studio.
