### ISSUE TITLE
Error when changing the ASS settings

### ISSUE THREAD

**Issue by roiebh** [phpBB-Studio/AdvancedShopSystem#12]
**Describe the bug**
When trying to submit changes on the ASS settings (in ACP) I'm getting the following error:
```
BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/includes/functions_module.php
LINE: 565
CALL: trigger_error()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()
```

**To Reproduce**
1. Go to 'ACP'
2. Click on 'extensions
3. Click on 'Advanced shop system >settings
3. Scroll down to 'Submit' and click.

**Expected behavior**
The changes do apply although the error appears.

**Screenshots**
<img width="1411" alt="Screen Shot 2020-06-02 at 9 32 18 AM" src="https://user-images.githubusercontent.com/64873142/83526122-f6816d80-a4b3-11ea-9375-14bf0495e858.png">

**Desktop (please complete the following information):**
 - OS: [ iOS]
 - Browser [chrome]

**Smartphone (please complete the following information):**
 - Version [80.0.3987.163]

**Additional context**

**Comment by 3D-I** [comment]
I don't have this error.

Try using English as your language.

**Comment by roiebh** [comment]
I realize that I'm getting this error if I'm using permission of another user (when using: try user's permission).

**Comment by 3D-I** [comment]
Thanks.
