### ISSUE TITLE
Recent Items blank

### ISSUE THREAD

**Issue by roiebh** [phpBB-Studio/AdvancedShopSystem#13]
**Describe the bug**
On the main screen of the shop, the recent item block doesn't show any pictures.
**Expected behavior**
It should show a picture or few pictures as a slide show.
**Screenshots**
<img width="1237" alt="Screen Shot 2020-06-10 at 8 55 28 AM" src="https://user-images.githubusercontent.com/64873142/84270240-61f0be00-aaf8-11ea-93b3-818671deb736.png">

**Desktop (please complete the following information):**
 - OS: [MACOS]
 - Browser [chrome]
 - Version [latest]

**Additional context**
I Also tried to set one picture or less/more/turn off auto slide etc.

**Comment by mrgoldy** [comment]
Well, you have a lot of extensions installed with various JS files that might interfere. I would suggest disabling them one by one and checking if that solves the issue. As a lot of your extensions have JS files that may interferce, eg jQuery UI Custom, Polyfills, etc.. 
So please switch the British English language pack and the Prosilver style.
Then start disabling one extension at a time and see if that solves the issue.

Alternatively, could you have a more specific look like so: 
![image](https://user-images.githubusercontent.com/15745936/84386780-36ea9500-abf2-11ea-8199-ea1a8d422fc2.png)
