### ISSUE TITLE
enable web hooks?

### ISSUE THREAD

**Issue by YiMeChen** [phpBB-Studio/AdvancedShopSystem#15]
Hi,

Thanks for this extension! 
I'm not sure if this has been asked before, but has not found anything similar to the kind in the issues or any other pages.

Is there a way to add custom web hooks on user purchase as well as item "usage" through their inventory? 

Or even a custom item_type extension to allow web hooks.. This would definitely make things easier for a lot of folks to adapt the systems. There hasn't been much information i can dig up on custom extensions, though some pages describes the possibility. If you can point me in the write direction that would be great!

Thanks!

**Comment by 3D-I** [comment]
Could you please elaborate your question a bit? I am not quite sure of what you are asking for, sorry.

**Comment by YiMeChen** [comment]
Sure! My questions is basically how to implement web-hooks into the current existing workflow.

To demonstration this using the file item type.

1. After a user success purchase:
![purchaseSuccess](https://user-images.githubusercontent.com/21165843/89686299-1d9d5680-d8cc-11ea-8f23-92ca85b6dd5b.JPG)

- how to implement a POST request to an custom web-hook url on the newly generated inventory data. 

![inventory_table](https://user-images.githubusercontent.com/21165843/89686411-4faeb880-d8cc-11ea-9756-1c5eb3a1656e.JPG)

- The web-hook url will then perform additional desired functions using the data point upon a confirmed successful purchase.

2. After a user success download (using an item) file:
![useSuccess](https://user-images.githubusercontent.com/21165843/89686842-16c31380-d8cd-11ea-8235-4971a01508c8.JPG)

- Implement POST request to another custom web-hook url that confirms the success use of the item, then perform some additional functions for fulfillment. With pretty much the same post data as the above on user_id, item_id, etc, 

Just the post requests to web-hook urls and shouldn't have to change any current workflow of the system. Hope this provides a better picture. It might not be the best example with the "File" item type, but with web-hooks, there definitely more open for many purposes, such as purchasing access to certain scripts that resides at a server, or further customization and integrations with phpbb.

What i was thinking previous on the idea of a new "item_type" would be something like this. 

1. On item creation:
![item_creation fields](https://user-images.githubusercontent.com/21165843/89688867-1593e580-d8d1-11ea-97cf-37c28c0bb4ed.png)

- Identifier being custom field that can be anything from filename, script-path that is only used on the function within web-hook urls (passed from the post reqeust)

2. Then this item_type would only have to perform the necessary post requests on purchase and usage of the item.

Web-hooks are widely used, a more general and example, for instance like the Stripe payment checkout system. https://stripe.com/docs/webhooks (the doc may be a overkill really) Upon a transactions, web hooks are used for Stripe to reach you so you can perform additional function in accordance to the action initiated by the user.

Minor tweeks might be needed here and there from the description above, hope it explain more on my question end. Please let me know if anything need more explaining. 

Thanks!

**Comment by YiMeChen** [comment]
I was able to implement the webhook by creating a new custom item_type and slightly modifying the inventory_controller.php. Thanks for the extension!

**Comment by 3D-I** [comment]
Inded that's the way to go.

If you would like to share your code feel free to do it, it will be evaluated.

**Comment by YiMeChen** [comment]
Sure. I have to say i cut some corners. But, i'm happy to leave some code here for anyone who might also be interested in this in the future to get it to work for them.

1. Append following to ass/config/services_items.yml at end of file

> 
    phpbbstudio.ass.items.custom:
        class: phpbbstudio\ass\items\type\custom
        parent: phpbbstudio.ass.items.base
        shared: false
        # calls:
        #     - [set_files, ['@phpbbstudio.ass.files']]
        tags:
            - { name: phpbbstudio.ass.item }


2. Create new file ass/items/type/custom.php with following

> namespace phpbbstudio\ass\items\type;
use phpbbstudio\ass\exceptions\shop_item_exception;
class Custom extends base
{
	public function set_files(\phpbbstudio\ass\helper\files $files)
	{}

	/**
	 * {@inheritDoc}
	 */
	public function get_language_key()
	{
		return 'ASS_TYPE_CUSTOM';
	}

	/**
	 * {@inheritDoc}
	 */
	public function activate(array $data, $item_slug = "")
	{
		$url = 'https://PATH_TO_YOUR_WEBHOOK_DOMAIN/activate_success_webhook';
		$data = array(
			'inventory' => $data,
			'item_slug' => $item_slug
		);
		$options = array(
			'http' => array(
				'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
				'method'  => 'POST',
				'content' => http_build_query($data)
			)
		);
		$context  = stream_context_create($options);
		$result = file_get_contents($url, false, $context);

		if ($result === "error"){
			/**
			 * If webhook returns error, do not activate item
			 */
			throw new shop_item_exception(500, 'ASS_TYPE_CUSTOM_ERROR');
		}

		return $result;
	}

	/**
	 * {@inheritDoc}
	 */
	public function get_acp_template(array $data)
	{
		return '@phpbbstudio_ass/items/custom.html';
	}

	/**
	 * {@inheritDoc}
	 */
	public function validate_acp_data(array $data)
	{
		$errors = [];
		return $errors;
	}
}



3. Create an empty file as ass/adm/style/items/custom.html

4. Insert following to the $lang array at ass/language/en/ass_common.php

> 
	'ASS_TYPE_CUSTOM'					=> 'Use Item',
	'ASS_TYPE_CUSTOM_CONFIRM'			=> 'Are you sure you wish to use this item?',
	'ASS_TYPE_CUSTOM_LOG'				=> 'Used an item',
	'ASS_TYPE_CUSTOM_START'			=> 'Item consumed',
	'ASS_TYPE_CUSTOM_START_NOT'		=> 'Item cannot be consumed',
	'ASS_TYPE_CUSTOM_SUCCESS'			=> 'You have successfully used this item.',
	'ASS_TYPE_CUSTOM_TITLE'			=> 'Items',
	'ASS_TYPE_CUSTOM_ERROR'		=> 'The item cannot be used at this moment.',

5. Modify ass/controller/inventory_controller.php on the  'activate' switch, starting from line 417. 

> case 'activate':
					$type->set_category($category);
					$type->set_item($item);

					if (confirm_box(true))
					{
						try
						{
							/**
							 * $item->get_data() when testing seems to returning null
							 * Purpose for this if statement is to filter for items that is desired for the webhook
							 * slug name convension: place "_webhook" at the end of the slug field when creating the item, 
							 * This can then be be filtered within webhook function for itemName (following default naming convention)
							 * slug name and/or item name is also used in the webhook function to identify items for different webhook functions.
							 */
							if(strpos($item_slug, "_webhook") !== false){
								$success = $type->activate($row, $item_slug);
							}else{
								$success = $type->activate($item->get_data());
							}
						}
						catch (shop_item_exception $e)
						{
							$this->log_phpbb->add('admin', $this->user->data['user_id'], $this->user->ip, 'LOG_ACP_ASS_ITEM_TYPE_ERROR', time(), [$category->get_title(), $item->get_title()]);

							if (!$item->get_conflict())
							{
								if ($this->config['ass_deactivate_conflicts'])
								{
									$item->set_active(false);
								}

								$item->set_conflict(true)
									->save();

								$category->set_conflicts($category->get_conflicts() + 1)
									->save();
							}

							throw $e;
						}

						/**
						 * Display webhook result in ajax response dialog to provide a more dynamic webhook user experience.
						 */
						if(strpos($item_slug, "_webhook") !== false){
							$message = $success;
						}else{
							$message = !empty($success) ? $this->language->lang($type->get_language('success')) : 'Some error message';
						}
						$title = !empty($success) ? $this->language->lang($type->get_language('title')) : $this->language->lang('INFORMATION');	

						$count	= (int) $row['use_count'];

						if (!empty($success) && empty($success['file']))
						{
							$count++;
						}


6. Then on your webhook destination you can have something like this:

> 
function activate_success_webhook(){
    /**
     * This should only be called within custom item_type activate method using the Advanced Shop System
     *  Result is passed to the $success variable inside inventory_controller.php on 'activate' switch
     *  This method will filter the passed data to perform additional fulfillment functions
     */
    $data = $_POST;
    /**
     * get itemName by item_slug naming convention
     * by default, spaces are translated to "-" in item slug from item name on item creation
     */
    $itemName = str_replace("-"," ", str_replace("_webhook","",$data['item_slug']));
    $user_id = $data['inventory']['user_id'];
    $item_id = $data['inventory']['item_id'];

    if (strtolower($itemName) == "test"){
        echo "This is a test item webhook!";
    }else{
        echo "error";
        // print_r($data); //For testing purposes
    }
    /**
     * returning "error" will cause the ajax call to throw an exeception
     * upon this exception, Shop System will also mark this item to be with conflict
     */
}

**Comment by 3D-I** [comment]
Thanks, I am not completely sure this is the way to go especially modification to the `ass/controller/inventory_controller.php` on the 'activate' switch, which shouldn't be touched at all. Looks more like an hack than anything else to me. Anyway, @mrgoldy will surely put on this table his opinion too sooner or later.
