### ISSUE TITLE
Multiple items/stacking/bulk buy

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedShopSystem#2]
Allow users to purchase/gift multiple copies of an item at a time, or allow them to have more than one of that item.

**Comment by mrgoldy** [comment]
Thanks for your feature request.
Currently we just released this extension and are in the initial testing phase, making sure what we currently have works as intended. Feature requests will be opened on a later time.. Atleast not the day after release ;).

**Comment by mrgoldy** [comment]
Item stacking is now supported as of version 1.1.1-beta

**Comment by YiMeChen** [comment]
Hope i'm not missing something. I do see stacking option within inventory, but not an options to bulk purchase. 

Sort of adding a quantity field during purchase.

<img width="526" alt="Screen Shot 2020-08-14 at 11 07 48 PM" src="https://user-images.githubusercontent.com/21165843/90304313-603ed000-de84-11ea-8948-62d9f8d7a759.png">

Please let me know if i missed something that can allow this, if not, i would like to request this feature in future updates.

Thanks!
