### ISSUE TITLE
Item moderation

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedShopSystem#3]
Allowing administrators to view, and modify user's inventory, this is probably a huge feature request as it is.

**Comment by mrgoldy** [comment]
Thanks for your feature request.
Currently we just released this extension and are in the initial testing phase, making sure what we currently have works as intended. Feature requests will be opened on a later time.. Atleast not the day after release ;).

**Comment by mrgoldy** [comment]
Inventory moderation is now available as of 1.1.0-beta _(with a fix to permissions in 1.1.1-beta)_!
