### ISSUE TITLE
Item display issue

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedShopSystem#5]
**Describe the bug**
Users can view items inside categories that have been disabled if they are enabled.

**To Reproduce**
1. Have items in a category.
2. Disable category, but not the items.
3. go to the store page.
4. See error _suffer_.

**Expected behavior**
For items inside disabled categories too not display.

**Additional context**
at least it will bring you to a 403 page.

**Comment by 3D-I** [comment]
Have a look to permissions

![immagine](https://user-images.githubusercontent.com/480857/64892121-df73c480-d673-11e9-8d19-478a5ecf69d1.png)

**Comment by mrgoldy** [comment]
It was indeed correct that the items on the shop index did not check if the category was active, just if they theirselves are active. 

Thanks for reporting this.
This has been fixed on the local repository and will be included in the next release.

**Comment by 3D-I** [comment]
https://github.com/phpBB-Studio/AdvancedShopSystem/commit/801236322ab6bf4e7c919c03557592149109a039
