### ISSUE TITLE
User shops

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedShopSystem#6]
Totally forgot about this one, but it was one of the things I came up with on the feature request tirade I did yesterday, and would like to give credit to this post for reminding me. https://www.phpbb.com/community/viewtopic.php?p=15321391#p15321391

I feel it would be kinda rude if I didn't give some credit for physically suggesting it first.
But allowing users to 'sell' items in the shop, and be directly paid for it.

**Comment by 3D-I** [comment]
FWIW, pls post the details of such User shop, since the post you linked contains at least 3 distinct requests.

**Comment by RickKraut** [comment]
> 
> 
> FWIW, pls post the details of such User shop, since the post you linked contains at least 3 distinct requests.

Essentially, users would be allowed to add items to the shops, though filtered through the administration, and would be paid for any purchases of the items.

This can _'sort of'_ be achieved with the way the extension is currently set up, but requires a lot of work on the forum administrations part, instead of just checking off on the item, 
they would need to create the item listing, 
monitor its sales and add funds correspondingly to the user.

Instead, I propose that the user (who has permission to do so), 
can create an item listing,
the item listing gets sent to an approval queue of some kind,
if it gets approved then it will be displayed publicly, until the user takes it down,
if the user decides to edit it, those edits are postponed till they are approved then the item listing gets updated with those edits
or easier, the item gets taken down until the edits are approved.

**Comment by mrgoldy** [comment]
And you see the list of features you are requesting?

An entire market place, 
an interface for common users to create items,
Schema changes as now we need to list the author(s) of the item,
Additional permissions, 
moderation queue for administrators (and moderators),
settings for what and how users can create items.

Therefore, this will not be considered at this time.

**Comment by 3D-I** [comment]
That being said, I am cosing this request as Customization.

Feel free to request this new ext, namely `marketplace` at our website.

Thanks.
