### ISSUE TITLE
maximum price

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedShopSystem#7]
I set the price to 9,999,999,999,999. A ridicules number in and of itself, and it sent an error page. I figure since you were able to set a (no smaller than 0 catch, that you might want to set a cap (if you don't plan on changing the size for the sql table, you might want to set a maximum size catch to stop that error page, as some people might not understand what it means... even if they should.

**Comment by 3D-I** [comment]
`9999999999999.99` is currently the max allowed

**Comment by 3D-I** [comment]
Fixed locally.

**Comment by 3D-I** [comment]
https://github.com/phpBB-Studio/AdvancedShopSystem/commit/801236322ab6bf4e7c919c03557592149109a039
