### ISSUE TITLE
remove =

### ISSUE THREAD

**Issue by eunaumtenhoid** [phpBB-Studio/AdvancedShopSystem#8]
on phpbbstudio\ass\styles\all\template
line 4 need remove = of 
<i class="**=**icon shop-panel-icon{{ ITEM_PANEL_ICON }}"></i>
to
<i class="icon shop-panel-icon{{ ITEM_PANEL_ICON }}"></i>

**Comment by 3D-I** [comment]
You mean 

`			<i class="=icon shop-panel-icon{{ ITEM_PANEL_ICON }}"></i>`

in https://github.com/phpBB-Studio/AdvancedShopSystem/blob/08cd435aa7ccfc7249a5a5b5fe1d9001035a7872/styles/all/template/ass_item_panel.html#L4

I think.

Ok, thanks for reporting.

**Comment by mrgoldy** [comment]
This has been fixed as of version 1.1.1-beta
Once again thank you for reporting.
