### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by shywing** [phpBB-Studio/AdvancedShopSystem#9]
Receiving the following error. 

> phpbbstudio\ass\entity\category as category because the name is already in use in /srv/disk1/2575031/www/manganimeverse.com/ext/phpbbstudio/ass/operator/inventory.php on line 13

1. Attempting to view the “items” page from the ACP yields the error. 
2. Attempting to view the “Inventory” page from UCP yields the error. 

**Expected behavior**
Expected to be able to add items to the shop/being able to seen the inventory page.

**Board Information:**
 - PHPBB version: 3.2.8
 - PHP Version: 5.4.45

**Comment by 3D-I** [comment]
Confirmed, it happens on PHP `5.5.38` and `5.6.40`.

![immagine](https://user-images.githubusercontent.com/480857/66288740-a3cac400-e8da-11e9-91d3-cf0d83737eb3.png)


Solves using min. PHP 7 (tested with 7.0.33).

**Comment by mrgoldy** [comment]
Thank you for reporting this, this will be fixed with the next release!

**Comment by mrgoldy** [comment]
This has been fixed as of version 1.1.1-beta.
Once again thank you for reporting!
